# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-09-04 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_slate_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='start_status',
            new_name='confirmed',
        ),
        migrations.RemoveField(
            model_name='baseplayer',
            name='start',
        ),
        migrations.RemoveField(
            model_name='baseplayer',
            name='start_status',
        ),
        migrations.RemoveField(
            model_name='player',
            name='start',
        ),
        migrations.AddField(
            model_name='baseplayer',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='baseplayer',
            name='order',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='player',
            name='order',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='baseplayer',
            name='handedness',
            field=models.CharField(blank=True, default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='handedness',
            field=models.CharField(blank=True, default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='injury',
            field=models.CharField(blank=True, default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='opponent',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
