# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-09-04 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20210904_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='play_today',
        ),
        migrations.AlterField(
            model_name='player',
            name='confirmed',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='proj_delta',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='salary',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='uid',
            field=models.IntegerField(),
        ),
    ]
