# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-09-04 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_auto_20210904_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='proj_points',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
